In [10]:
import pandas as pd

In [11]:
df=pd.read_csv("C:/Users/Ibscai29.DGVC-MCA/Documents/iris.csvpd.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [12]:
df.isnull()

     sepal_length  sepal_width  petal_length  petal_width  class
0           False        False         False        False  False
1           False        False         False        False  False
2           False        False         False        False  False
3           False        False         False        False  False
4           False        False         False        False  False
..            ...          ...           ...          ...    ...
145         False        False         False        False  False
146         False        False         False        False  False
147         False        False         False        False  False
148         False        False         False        False  False
149         False        False         False        False  False

[150 rows x 5 columns]

In [16]:
df.isnull().sum()

sepal_length    0
sepal_width     1
petal_length    2
petal_width     0
class           3
dtype: int64

In [14]:
df["sepal_length"].fillna(0)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [17]:
df["sepal_length"]=df["sepal_length"].fillna(0)

np.float64(3.051677852348994)

In [21]:
df["sepal_width"]=df["sepal_width"].fillna(mn)

In [22]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    2
petal_width     0
class           3
dtype: int64

In [23]:
mn=df["petal_width"].median()
mn

1.3

In [24]:
df["petal_width"]=df["petal_width"].fillna(mn)

In [25]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    2
petal_width     0
class           3
dtype: int64

In [26]:
mn=df["petal_length"].mean()
mn

np.float64(3.788513513513514)

In [27]:
df["petal_length"]=df["petal_length"].fillna(mn)

In [28]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           3
dtype: int64

In [29]:
mn=df["class"].mode()
mn

0    Iris-versicolor
1     Iris-virginica
Name: class, dtype: object

In [45]:
df["class"]=df["class"].fillna(0)

In [46]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

In [47]:
df["sepal_width"]=df["sepal_width"].ffill()

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\Ibscai29.DGVC-MCA\Documents\adult.csv")
df.head()

,S.no,col A,balance,Education Status,col B,Martial Status,Dept,family Status,color,Gender,col C,col D,Age,Country,Salary
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
df.isnull()

,S.no,col A,balance,Education Status,col B,Martial Status,Dept,family Status,color,Gender,col C,col D,Age,Country,Salary
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,True,False,False,False,False,False,True,True,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
df.isnull().sum()

S.no                0
col A               0
balance             3
Education Status    0
col B               2
Martial Status      0
Dept                1
family  Status      1
color               1
Gender              1
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64

In [6]:
df["balance"]=df["balance"].fillna(0)

In [7]:
mn=df["balance"].mean()
mn

np.float64(162779.23076923078)

In [8]:
df.isnull().sum()

S.no                0
col A               0
balance             0
Education Status    0
col B               2
Martial Status      0
Dept                1
family  Status      1
color               1
Gender              1
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64

In [9]:
df["col B"]=df["col B"].fillna(0)

In [10]:
mn=df["col B"].mean()
mn

np.float64(9.576923076923077)

In [11]:
df.isnull().sum()

S.no                0
col A               0
balance             0
Education Status    0
col B               0
Martial Status      0
Dept                1
family  Status      1
color               1
Gender              1
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64

In [12]:
df["Dept"]=df["Dept"].fillna(0)

In [15]:
mn=df["Dept"].mode()
mn

0     Exec-managerial
Name: Dept, dtype: object

In [16]:
df.isnull().sum()

S.no                0
col A               0
balance             0
Education Status    0
col B               0
Martial Status      0
Dept                0
family  Status      1
color               1
Gender              1
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64

In [18]:
df["family  Status"]=df["family  Status"].fillna(0)

In [20]:
mn=df["family  Status"].mode()
mn

0     Husband
Name: family  Status, dtype: object

In [21]:
df.isnull().sum()

S.no                0
col A               0
balance             0
Education Status    0
col B               0
Martial Status      0
Dept                0
family  Status      0
color               1
Gender              1
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64

In [22]:
df["color"]=df["color"].fillna(0)

In [23]:
mn=df["color"].mode()
mn

0     White
Name: color, dtype: object

In [24]:
df.isnull().sum()

S.no                0
col A               0
balance             0
Education Status    0
col B               0
Martial Status      0
Dept                0
family  Status      0
color               0
Gender              1
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64

In [25]:
df["Gender"]=df["Gender"].fillna(0)

In [26]:
mn=df["Gender"].mode()
mn

0     Male
Name: Gender, dtype: object

In [27]:
df.isnull().sum()

S.no                0
col A               0
balance             0
Education Status    0
col B               0
Martial Status      0
Dept                0
family  Status      0
color               0
Gender              0
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64

In [28]:
 df["Gender"]=df["Gender"].ffill()

In [29]:
df.isnull().sum()

S.no                0
col A               0
balance             0
Education Status    0
col B               0
Martial Status      0
Dept                0
family  Status      0
color               0
Gender              0
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64

In [31]:
df["balance"]=df["balance"].bfill()

In [32]:
df.isnull().sum()

S.no                0
col A               0
balance             0
Education Status    0
col B               0
Martial Status      0
Dept                0
family  Status      0
color               0
Gender              0
col C               0
col D               0
Age                 0
Country             0
Salary              0
dtype: int64